XG/Areas/Configuration/Controllers/BaseConfigurationController.cs
using XG.Controllers;
using Microsoft.AspNetCore.Mvc;

namespace XG.Areas.Configuration.Controllers
{
	[Area("Configuration")]
	[Route("Configuration/[controller]")]
    public class BaseConfigurationController: BaseController
    {
        public BaseConfigurationController()
        {
        }
    }
}

XG/Areas/Configuration/Controllers/CompetitionsController.cs
using Microsoft.AspNetCore.Mvc;
using XG.Controllers;
using XG.Business.Services.Interfaces;
namespace XG.Areas.Configuration.Controllers
{
  public class CompetitionsController: BaseConfigurationController
  {
        private ICompetitionService _competititionService;
        public CompetitionsController(ICompetitionService competitionService)
        {
            this._competititionService = competitionService;
        }

        public IActionResult Index()
        {
          return View();
        }
  }
}

XG/Areas/Configuration/Controllers/MatchesController.cs
using Microsoft.AspNetCore.Mvc;
using XG.Controllers;
using XG.Business.Services.Interfaces;

namespace XG.Areas.Configuration.Controllers
{
    public class MatchesController: BaseConfigurationController
	{
		private IMatchService _matchService;
		public MatchesController(IMatchService matchService)
		{
			this._matchService = matchService;
		}

        public IActionResult Index()
        {
          return View();
        }
  }
}

XG/Areas/Configuration/Controllers/SeasonsController.cs
using Microsoft.AspNetCore.Mvc;
using XG.Controllers;
using XG.Business.Services.Interfaces;

namespace XG.Areas.Configuration.Controllers
{
    public class SeasonsController: BaseConfigurationController
    {
        private ISeasonService _seasonService;
        public SeasonsController(ISeasonService seasonService)
        {
            this._seasonService = seasonService;
        }

        public IActionResult Index()
        {
          return View();
        }
    }
}

XG/Areas/Configuration/Controllers/TeamsController.cs
using XG.Business.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace XG.Areas.Configuration.Controllers
{
    public class TeamsController: BaseConfigurationController
    {
        private ITeamService _teamService;
        public TeamsController(ITeamService teamService)
        {
            this._teamService = teamService;
		}

		public IActionResult Index()
		{
			return View();
		}
    }
}

XG/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace XG.Controllers
{
  public class BaseController: Controller
  {
    
  }
}

XG/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace XG.Controllers
{
    public class HomeController : BaseController
    {
        public IActionResult Index()
		    {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

XG/Areas/Configuration/Views/Competitions/Index.cshtml
@{
  Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts
{
    <script src="~/ts/pagedTableModel.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
	        debugger;
	    });
	</script>
}

XG/Views/Home/Index.cshtml
@section scripts
{
        <script src="~/ts/pagedTableModel.js"></script>
}

XG/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Routing
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["XG"] - XG</title>

  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/lib/font-awesome-4.7.0/css/font-awesome.min.css">
    <environment names="Development">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
  <environment names="Staging,Production">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
  </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">XG</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-cogs"></i> Configure
                        <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a asp-area="Configuration" asp-controller="Seasons" asp-action="Index"><i class="fa fa-calendar"></i> Seasons</a></li>
                        <li><a asp-area="Configuration" asp-controller="Competitions" asp-action="Index"><i class="fa fa-trophy"></i> Competitions</a></li>
                        <li><a asp-area="Configuration" asp-controller="Teams" asp-action="Index"><i class="fa fa-users"></i> Teams</a></li>
                        <li><a asp-area="Configuration" asp-controller="Matches" asp-action="Index"><i class="fa fa-futbol-o"></i> Matches</a></li>
                      </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - XG</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>